# The script is a Lambda function that checks and reports the status of EBS snapshots created by a backup function. 
# It identifies snapshots with a specific description, checks their status (pending, completed, or failed), and generates a report

import boto3
import traceback
import time

def get_snapshot_name(snapshot_obj):
    ss_name = snapshot_obj['SnapshotId']
    # Find name tag
    if 'Tags' in snapshot_obj:
                for tags in snapshot_obj['Tags']:
                    if tags["Key"] == 'Name':
                        ss_name = tags["Value"]
    return ss_name                   

def lambda_handler(event, context):
    ec2 = boto3.client('ec2')
    ec2resource = boto3.resource('ec2')

    # list the snapshots generated by lambda function
    result = ec2.describe_snapshots(Filters=[{'Name': 'description', 'Values': ['Created by Lambda backup function ebs-snapshots']}])
    report = {}
    for Snapshot in result['Snapshots']:
        snapshot_name = get_snapshot_name(Snapshot)
        try:         
            # Get snapshot resource
            snap = ec2resource.Snapshot(Snapshot['SnapshotId'])
                        
            if snap.state == 'pending':
                print(f"{snapshot_name}: {snap.state}")
                report[snapshot_name]='PENDING'
            elif snap.state == 'completed':
                report[snapshot_name]='SUCCESS'
            else:
                report[snapshot_name]='FAILED'
        except Exception as e: 
            report[snapshot_name]='FAILED'
            print(f"{snapshot_name}")
            print(e)
            traceback.print_exc()

    for key,value in report.items():
        print(f"{key}: {value}")

    print('Snapshot status check completed')
